custom_file_path:
  style: source/_data/styles.styl

scheme: Mist

menu:
  主页: / || fa fa-home
  关于: /about/ || fa fa-user
  标签: /tags/ || fa fa-tags
  分类: /categories/ || fa fa-th
  归档: /archives/ || fa fa-archive

menu_settings:
  icons: true
  badges: false

sidebar:
  position: left
  display: hide
  offset: 12

avatar:
  url: /images/me.jpg

social:
  GitHub: https://github.com/cyh123 || fab fa-github
  StackOverflow: https://stackoverflow.com/users/9581306/yunhai || fab fa-stack-overflow

social_icons:
  enable: true
  icons_only: false
  transition: false

toc:
  enable: true
  number: true
  wrap: false

excerpt_description: true

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: false
    another_day: true
  categories: true

fancybox: true

comments:
  style: tabs
  active: valine
  storage: true
  lazyload: false

valine:
  enable: true
  appId: jtQLIeV6jE3JEz552dDc8drD-gzGzoHsz
  appKey: ntTvuVT0T22Vn198alyrXuKA
  placeholder: 留下你的问题
  avatar: mm
  meta: [nick, mail, link]
  pageSize: 10
  visitor: false
  comment_count: true
  recordIP: false

leancloud_visitors:
  enable: true
  app_id: jtQLIeV6jE3JEz552dDc8drD-gzGzoHsz
  app_key: ntTvuVT0T22Vn198alyrXuKA
  security: true
  betterPerformance: false

local_search:
  enable: true
  top_n_per_article: 1
  unescape: false
  preload: false
